/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SelectRouteImport } from './routes/select'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as BadgeRouteImport } from './routes/badge'
import { Route as IndexRouteImport } from './routes/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeRoute = BadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badge': typeof BadgeRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/select': typeof SelectRoute
  '/test': typeof TestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badge': typeof BadgeRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/select': typeof SelectRoute
  '/test': typeof TestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badge': typeof BadgeRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRoute
  '/select': typeof SelectRoute
  '/test': typeof TestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badge'
    | '/badges'
    | '/dashboard'
    | '/login'
    | '/results'
    | '/select'
    | '/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badge'
    | '/badges'
    | '/dashboard'
    | '/login'
    | '/results'
    | '/select'
    | '/test'
  id:
    | '__root__'
    | '/'
    | '/badge'
    | '/badges'
    | '/dashboard'
    | '/login'
    | '/results'
    | '/select'
    | '/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgeRoute: typeof BadgeRoute
  BadgesRoute: typeof BadgesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResultsRoute: typeof ResultsRoute
  SelectRoute: typeof SelectRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge': {
      id: '/badge'
      path: '/badge'
      fullPath: '/badge'
      preLoaderRoute: typeof BadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgeRoute: BadgeRoute,
  BadgesRoute: BadgesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResultsRoute: ResultsRoute,
  SelectRoute: SelectRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
